version: '3.9'

services:
  db:
    image: postgres:15
    ports:
      - '9305:5432'
    environment:
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 30s
      retries: 5
    restart: always
